persistence:
  postgresql:
    secretRef:
      name: backstage-psql-secret-rhdh
      userKey: POSTGRES_USER
      passwordKey: POSTGRES_PASSWORD
    serviceRef:
      name: backstage-psql-rhdh
      port: 5432
      databaseName: backstage_plugin_orchestrator
      databaseSchema: greeting

image: 
  repository: quay.io/redhat_pe_workshop/swf-create-ocp-namespace-swt
  tag: b67f0b5

backstage:
  softwareTemplateNamespaceSmall:
  softwareTemplateNamespaceLarge:

secret:
  backstageToken: orchestrator-backstage-backend-token
  gitlabToken: orchestrator-gitlab-token